# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 18:38
from __future__ import unicode_literals

import apps.product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20171119_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.product.models.upload_image_path, verbose_name='image'),
        ),
    ]
