# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20171130_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='featured'),
        ),
    ]
