# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20171203_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='abc', verbose_name='slug'),
            preserve_default=False,
        ),
    ]
